### ISSUE TITLE
`whisper`ing to oneself has wrong error message

### ISSUE THREAD

**Issue by prophnoran** [prophecymud/prophecy-issues#14]
```
993/1389H 491/568M 147/384V a:1000 7447tnl EU   sneak: >
whisper self whargle bargle
You can't whisper to yourself.
You whisper 'whargle bargle' to Khorlon.
```

Well... can I whisper to myself or can't I? (For the record, I like being able to whisper to myself)

**Comment by anhegofcherek** [comment]
Neat, a missing `return`, thanks

I've dropped it for now, because you can already `tell self` and I'd have needed to refactor a bunch of the whisper logic to make it look ok when you `whisper self`, sorry!

**Comment by prophnoran** [comment]
Noooo all my scripts will break :).
