### ISSUE TITLE
Can't log in characters when a new character is being in the process of being made

### ISSUE THREAD

**Issue by kerowa** [prophecymud/prophecy-issues#23]
Seems to be a replicate of Issue prophecymud/go-prophecy-issues#18 .  Does not seem to have been fixed.  Get error of 'That name is being created already"

**Comment by anhegofcherek** [comment]
Reproduced, and possibly fixed - I just need to test it

**Comment by anhegofcherek** [comment]
Finally fixed, sorry for the back and forth here!
