### ISSUE TITLE
continual light

### ISSUE THREAD

**Issue by Ranfir** [prophecymud/prophecy-issues#9]
I'm pretty sure that this used to allow you to add the "glow" flag to objects way back in 1997. Was this removed on purpose? Or just broken?

Note that this only matters if the glow flag is still affects enchanting success rates.
```
help continual
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Keywords: Continual_Light
Category: Spells
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Syntax: cast 'continual light'
Syntax: cast 'continual light' <object>

This spell creates a ball of light, which you can hold as a light source.
The ball of light will last indefinitely. It may also be used on an object
to give it an enchanted glow.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

**Comment by anhegofcherek** [comment]
I think I removed a lot of the glow/hum stuff years ago because 99% of it was irritation - I've updated the helpfile in https://github.com/prophecymud/helps/commit/82a8a0625f17f03ee65b68916722b751532e0b9d - thanks!
